"""
report_generator.py
Builds a downloadable PDF report combining the executive summary and risk scores.
"""

import tempfile
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)


def generate_pdf_report(doc_name: str, summary_text: str, risk_data: dict) -> str:
    """
    Build a PDF report and return the path to the generated file.
    risk_data is expected to have: overall_score, categories (dict), justifications (dict)
    """
    output_path = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf").name

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=20, spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"], fontSize=10, textColor=colors.grey
    )
    heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"], spaceBefore=16, spaceAfter=8
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=10.5, leading=15
    )

    story = []

    # --- Header ---
    story.append(Paragraph("AI Due Diligence Copilot — Report", title_style))
    story.append(Paragraph(f"Document analyzed: {doc_name}", subtitle_style))
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%B %d, %Y at %H:%M')}", subtitle_style))
    story.append(Spacer(1, 20))

    # --- Executive Summary ---
    story.append(Paragraph("Executive Summary & Risk Assessment", heading_style))
    for line in summary_text.split("\n"):
        if line.strip():
            story.append(Paragraph(line.strip(), body_style))
            story.append(Spacer(1, 4))

    story.append(Spacer(1, 12))

    # --- Risk Score Table ---
    story.append(Paragraph("Risk Score Breakdown", heading_style))
    story.append(Paragraph(
        f"<b>Overall Risk Score: {risk_data['overall_score']} / 10</b>", body_style
    ))
    story.append(Spacer(1, 10))

    table_data = [["Category", "Score (1-10)", "Justification"]]
    for category, score in risk_data["categories"].items():
        justification = risk_data.get("justifications", {}).get(category, "")
        table_data.append([category, str(score), Paragraph(justification, body_style)])

    risk_table = Table(table_data, colWidths=[1.3 * inch, 1 * inch, 3.7 * inch])
    risk_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(risk_table)

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>This report was generated by an AI system for informational purposes only "
        "and should be reviewed by a qualified analyst before use in decision-making.</i>",
        ParagraphStyle("Disclaimer", parent=styles["Normal"], fontSize=8.5, textColor=colors.grey),
    ))

    doc.build(story)
    return output_path